config/routes.rb
Fundit::Application.routes.draw do
  get "home/index"

  resources :organizations do
    member do
      post 'follow'
      delete 'unfollow'
    end
    collection do
      get 'new_stripe'
    end

    resources :events
  end

  resources :events
  
  resources :volunteers

  resources :volunteers do
    resources :participations do
      member do
        get 'donate', :as => 'donate', :action => 'show'
        post 'donate'
        get 'thank', :as => 'thank', :action => 'thank_form'
        post 'thank'

        get 'offline_donate', :as => 'offline_donate', :action => 'offline_donate_form'
        post 'offline_donate'
      end
    end
  end

  match '/login' => 'sessions#new', :via => :get, :as => 'login'
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :via => :delete, :as => 'logout'

  root :to => 'home#index'

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  attr_accessible :goal, :note
  belongs_to :event
  belongs_to :volunteer
  has_many :donations
  has_many :offline_donations

  validates :event_id, :uniqueness => {:scope => :volunteer_id}
  validates :goal, :presence => :true, :numericality => {:integer_only => true}
  validates :event_id, :volunteer_id, :presence => true
  
  def donation_sum
    return donations.sum(:amount)
  end
  
  def offline_donation_sum
  	return offline_donations.sum(:amount)
  end
  
  def donation_percent
  	return donations.sum(:amount)*100 / goal
  end
  
  def offline_donation_percent
  	return offline_donations.sum(:amount)*100 / goal
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_filter :require_user, :except => [:show, :donate_form, :donate]
  before_filter :require_volunteer, :except => [:show, :donate_form, :donate]
  before_filter :find_participation, :except => [:new, :create]
  before_filter :require_ownership, :only => [:edit, :update, :thank_form,
                                              :thank, :offline_donate,
                                              :offline_donate_form]
  before_filter :find_donation, :only => [:thank, :thank_form]

  # GET /volunteers/1/participations/1
  # GET /volunteers/1/participations/1.json
  def show
    @participation = Participation.find(params[:id])
    @volunteer = @participation.volunteer

    @offline_perc = @participation.offline_donation_percent
    @online_perc = @participation.donation_percent
    @donation = Donation.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participation }
    end
  end

  # GET /volunteers/1/participations/new
  # GET /volunteers/1/participations/new.json
  def new
    # if the volunteer id is 0, it means the user tried to participate while
    # logged out, got redirected to login, and then redirected back. Redirect
    # them to the right url.
    if params[:volunteer_id] == '0'
      return redirect_to new_volunteer_participation_url(current_user, request.query_parameters)
    end

    @participation = Participation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participation }
    end
  end

  # GET /volunteers/1/participations/1/edit
  def edit
    @participation = Participation.find(params[:id])
  end

  # POST /volunteers/1/participations
  # POST /volunteers/1/participations.json
  def create
    @participation = Participation.new(params[:participation])
    @participation.volunteer = current_user
    @participation.event = Event.find(params[:event_id])

    respond_to do |format|
      if @participation.save
        format.html { redirect_to volunteer_participation_url(current_user, @participation), notice: 'Participation was successfully created.' }
        format.json { render json: @participation, status: :created, location: @participation }
      else
        format.html { render action: "new" }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /volunteers/1/participations/1
  # PUT /volunteers/1/participations/1.json
  def update
    @participation = Participation.find(params[:id])

    respond_to do |format|
      if @participation.update_attributes(params[:participation])
        format.html { redirect_to volunteer_participation_url(current_user, @participation), notice: 'Participation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /volunteers/1/participations/1
  # POST /volunteers/1/participations/1.json
  def donate
    @donation = Donation.new(params[:donation])
    @donation.participation = @participation

    respond_to do |format|
      if @donation.save
        format.html { redirect_to volunteer_participation_url(@participation.volunteer, @participation), notice: 'Donation was successful. Thank you for your contribution.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "show" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  def offline_donate_form
  	@offline_donation = OfflineDonation.new
  end

  # POST /volunteers/1/participations/1
  # POST /volunteers/1/participations/1.json
  def offline_donate
    @offline_donation = OfflineDonation.new(params[:offline_donation])
    @offline_donation.participation = @participation

    respond_to do |format|
      if @offline_donation.save
        format.html { redirect_to volunteer_participation_url(@participation.volunteer, @participation), notice: 'Offline donation was logged successfully' }
        format.json { render json: @offline_donation, status: :created, location: @donation }
      else
        format.html { render action: "offline_donate_form" }
        format.json { render json: @offline_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /volunteers/1/participations/1/thank?donation_id=1
  def thank_form
  end

  # POST /volunteers/1/participations/1/thank
  def thank
    Pony.mail :to => "\"#{@donation.name}\" <#{@donation.email}>",
              :from => "\"#{@volunteer.name}\" <#{@volunteer.email}>",
              :subject => "Thank you for supporting me in #{@participation.event.name}",
              :body => params[:message]

    @donation.thank_you_sent = true
    @donation.save!
    redirect_to volunteer_participation_url(@participation.volunteer, @participation)
  end

  private

  def find_participation
    @participation = Participation.find(params[:id])
    @volunteer = @participation.volunteer
    @event = @participation.event
  end

  def find_donation
    if params[:donation_type] == 'offline'
      @donation = OfflineDonation.find_by_id(params[:donation_id])
    else
      @donation = Donation.find_by_id(params[:donation_id])
    end
  end

  def require_ownership
    unless @participation.volunteer == current_user
      redirect_to root_url, :alert => "You don't own that participation."
    end
  end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
  def interpolate_email email, participation, donor=nil
    email ||= ''
    donor ||= 'Anonymous'

    event = participation.event
    org = event.organization.name
    date = event.date
    name = event.name
    volunteer = participation.volunteer.name
    link = 'https://fundit.herokuapp.com' + volunteer_participation_path(volunteer, participation)

    email.gsub('{{date}}', date.strftime('%B %d, %Y')).
          gsub('{{org}}', org).
          gsub('{{name}}', name).
          gsub('{{link}}', link).
          gsub('{{volunteer}}', volunteer).
          gsub('{{donor}}', donor)
  end
end

app/views/participations/_donate_form.html.erb
	<%= form_for @donation, :url => donate_volunteer_participation_path(@participation.volunteer, @participation),
										:html => { :class => 'form-horizontal donate-form', :id => 'stripe-payment-form' } do |f| %>

	<div class="alert alert-error alert-block" style="<%=(@donation.errors.any? ? '' : 'display: none')%>">
		<% if @donation.errors.any? %>
			<h4><%= pluralize(@donation.errors.count, "error") %> while checking out</h4>
			<ul>d
				<% @donation.errors.full_messages.each do |msg| %>
					<li><%= msg %>
				<% end %>
			</ul>
		<% end %>
	</div>

	<div class="control-group">
		<label class="control-label">Donation Amount</label>
		<div class="controls">
			<div class="input-prepend input-append">
				<span class="add-on">$</span>
				<%= f.text_field :amount, :size => 4, :class => 'input-mini amount-input' %>
				<span class="add-on">.00</span>
			</div>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">Name</label>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">Email</label>
		<div class="controls">
			<%= f.text_field :email %>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">Card Number</label>
		<div class="controls">
			<input type="text" size="20" autocomplete="off" class="card-number" />
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">
			CVC
			<a href="#" rel="popover"
			   data-content="Your CVC is usually located on the back of your card."
			   data-original-title="Where is my CVC?"
			   data-trigger="hover"
			   onclick="javascript:return false;">
			   	<i class="icon-question-sign"></i>
			</a>
		</label>
		<div class="controls">
			<input type="text" size="4" autocomplete="off" class="card-cvc input-mini" />
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">Expiration</label>
		<div class="controls">
			<input type="text" size="2" autocomplete="off" class="card-expiry-month input-mini" placeholder="MM" maxlength="2"/>
			/
			<input type="text" size="4" autocomplete="off" class="card-expiry-year input-mini" placeholder="YYYY" maxlength="4"/>

		</div>
	</div>

	<div class="control-group">
		<label class="control-label">Message</label>
		<div class="controls">
			<%= f.text_area :message, :rows=>5 %>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label">
			Keep Private
			<a href="#" rel="popover"
			   data-content="Email is always private. Name, amount, and message are always shown
				to the volunteer you're contributing to, but you can choose to not
				show them publicly."
			   data-original-title="What does this mean?"
			   data-trigger="hover"
			   onclick="javascript:return false;">
			   	<i class="icon-question-sign"></i>
			</a>
		</label>
		<div class="controls">
			<label class="checkbox">
				<%= f.check_box :is_name_private %> Name
			</label>
			<label class="checkbox">
				<%= f.check_box :is_amount_private %> Amount
			</label>
			<label class="checkbox">
				<%= f.check_box :is_message_private %> Message
			</label>
		</div>

	</div>

	<div class="control-group form-actions">
		<%= f.submit 'Donate', :class => 'btn btn-primary submit-button' %>
	</div>
<% end %>


<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<script type="text/javascript">
  Stripe.setPublishableKey("<%= j @participation.event.organization.stripe_pub_key %>");
</script>

app/views/participations/_form.html.erb
<% if @participation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

    <ul>
    <% @participation.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for [current_user, @participation] do |f| %>

  <% if params[:event_id] %>
    <%= hidden_field_tag 'event_id', params[:event_id] %>
  <% end %>

  <div class="control-group">
    <%= f.label :note, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :note, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :goal, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :goal, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/participations/edit.html.erb
<div class="page-header">
  <h1>Edit Participation</h1>
</div>
<%= render :partial => 'form' %>

app/views/participations/new.html.erb
<div class="page-header">
  <h1>New Participation</h1>
</div>
<%= render :partial => 'form' %>

app/views/participations/offline_donate_form.html.erb
<div class="page-header">
  <h1>Log Offline Donation</h1>
</div>

<%= form_for @offline_donation, :url => offline_donate_volunteer_participation_path(@participation.volunteer, @participation) do |f| %>

  <div class="alert alert-error alert-block" style="<%=(@offline_donation.errors.any? ? '' : 'display: none')%>">
    <% if @offline_donation.errors.any? %>
      <h4><%= pluralize(@offline_donation.errors.count, "error") %> with submission:</h4>
      <ul>
        <% @offline_donation.errors.full_messages.each do |msg| %>
          <li><%= msg %>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="control-group padding-bottom">
    <label class="control-label">Donation Amount</label>
    <div class="controls">
      <div class="input-prepend input-append">
        <span class="add-on">$</span>
        <%= f.text_field :amount, :size => 4, :class => 'input-mini amount-input' %>
        <span class="add-on">.00</span>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Donor Name</label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Donor Email</label>
    <div class="controls">
      <%= f.text_field :email %>
      <span class="help-inline">
        Optional.
      </span>
    </div>
  </div>

  <div class="control-group padding-bottom">
    <label class="control-label">Donation Type</label>
    <label class="radio">
    	<%= f.radio_button(:donation_type, "check") %>
    	Check
    </label>
    <label class="radio">
    	<%= f.radio_button(:donation_type, "cash") %>
    	Cash
    </label>
  </div>

	<div class="control-group padding-bottom">
		<label class="control-label">Do Not Display</label>
		<div class="controls">
			<label class="checkbox">
				<%= f.check_box :is_name_private %> Name
			</label>
			<label class="checkbox">
				<%= f.check_box :is_amount_private %> Amount
			</label>
		</div>
	</div>

  <div class="form-actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary submit-button' %>
    <%= link_to 'Cancel', volunteer_participation_url(@participation.volunteer, @participation), :class => 'btn' %>
  </div>
<% end %>

app/views/participations/show.html.erb
<div class="container-fluid">
    <div class="info-header">
        <div class="row">
            <div class="span2">
                <%= profile_event_image_tag_for @participation.event %>
            </div>
						<div class="span6 details">
								<p class="participation-support">
										Support <%= @volunteer.name %>'s
										participation in:
								</p>
								<p class="participation-date">
										<%= @event.date.strftime('%B %d, %Y') %>
								</p>
								<p class="participation-event">
										<%= @event.name %>
								</p>
								<div class="participation-info-links">
										<%= link_to volunteer_path(@volunteer)  do %>
												<i class="icon-user"></i>
												More about <%= @volunteer.name %>
										<% end %>

										<%= link_to organization_event_path(@event.organization, @event)  do %>
												<i class="icon-calendar"></i>
												More about this event
										<% end %>
								</div>
						</div>
						<% if @volunteer == current_user %>
							<div class="controls-header span3">
								<%= link_to edit_volunteer_participation_path(@volunteer, @participation), :class => 'participation-control-link' do %>
										Edit Participation Page
								<% end %>

								<%= link_to offline_donate_volunteer_participation_path(@volunteer, @participation), :class => 'participation-control-link' do %>
										Log Offline Donation
								<% end %>

								<div class="dropdown">
									<a class="dropdown-toggle share-participation" data-toggle="dropdown" href="#">
											<i class="icon-plus"></i>
											Share
											<b class="caret"></b>
									</a>
									<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
										<li>
											<a href="#" class="twitter-link">
													<i class="icon-twitter"></i>
													Twitter
											</a>
										</li>
										
										<li>
											<a href="#" class="facebook-link">
													<i class="icon-facebook"></i>
													Facebook
											</a>
										</li>
										
										<li>
												<a href="#" class="email-link">
														<i class="icon-envelope"></i>
														Email
												</a>
										</li>
									</ul>
								</div>
							</div>
						<% end %>
        </div>
        
    </div>




  <div class="row-fluid participation-body">
		<div class="span7 sidebar">
			<div class="row">
				<div class="span3 statistic offset1">
					<small> Raised Online</small>
					<div class="row">
						<div class="span3">
							<strong class="text-orange"> $<%= @participation.donation_sum %> </strong>
						</div>
					</div>
				</div>
				<div class="span3 statistic offset1">
					<small> Raised Offline</small>
					<div class="row">
						<div class="span3">
							<strong class="text-blue"> $<%= @participation.offline_donation_sum %> </strong>
						</div>
					</div>
				</div>
				<div class="span1 statistic offset1">
					<small> Goal </small>
					<div class="row">
						<div class="span1">
							<strong> $<%= @participation.goal %> </strong>
						</div>
					</div>
				</div>
			</div>
			<div class="row progress-row">
				<div class="span11">
					<div class="progress">
						<div class="bar bar-warning" id="onlineBar"></div>
						<div class="bar bar-info" id="offlineBar"></div>

					</div>
				</div>
			</div>
			<div class="biobox" >
				<strong>A Message From <%= @participation.volunteer.name%></strong>
				<p><%= @participation.note %></p>
			</div>
			<div class="donation-history">

				<h2> Donation History </h2>
                <% if @participation.donations.empty? && @participation.offline_donations.empty?%>
                    <p>No donations yet.</p>
                <% else %>
    				<table class="table">
    					<% (@participation.donations + @participation.offline_donations).reverse.each do |donation| %>
							<tr>
								<td class="date"> <%= donation.created_at ? donation.created_at.strftime('%m/%d') : 'none' %></td>
								<% if @volunteer == current_user %>
								<td>
									<%= donation.private_history_message %>
									<% if donation.kind_of? Donation %>
										<% if !donation.message.nil? %>
										<p class="message"><%= donation.message %></p>
										<% end %>
									<% end %>
								</td>
								<td>

									<% if donation.email? and !donation.thank_you_sent? %>
										<%= link_to '<i class="icon-envelope icon-large black"></i>'.html_safe,
																thank_volunteer_participation_path(
																	@volunteer,
																	@participation,
																	:donation_id => donation.id.to_s,
																										:donation_type => (donation.kind_of?(OfflineDonation) ? 'offline' : 'online')) %>
									<% elsif donation.email? %>
										<i class="icon-envelope icon-large inactive"></i>
									<% end %>

								</td>
								<% else %>
									<% if donation.all_private != true %>
										<td>
											<%= donation.share_history_message %>
											<% if donation.kind_of? Donation %>
												<% if !donation.message.nil? && !donation.is_message_private %>
													<p class="message"><%= donation.message %></p>
												<% end %>
											<% end %>
										</td>
									<% end %>
								<% end %>
							</tr>
            			<% end %>
    				</table>
                 <% end %>
    		</div>
		</div>
		<div class="span6 main-content" id="donationForm">
			<div class="hero-unit">
				<div class="hero-unit-header">
					<h2> Donate Now! </h2>
				</div>
				<%= render :partial => 'donate_form' %>
			</div>
		</div>
	</div>
</div>

<% content_for :additional_scripts do %>
    <script type="text/javascript">
			var online_perc = <%= @online_perc %>;
			var offline_perc = <%= @offline_perc %>;
			$('#onlineBar').css('width', (online_perc)+'%');
			$('#offlineBar').css('width', (offline_perc)+'%');
    </script>
    <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
	<script type="text/javascript">
	  Stripe.setPublishableKey("<%= j @participation.event.organization.stripe_pub_key %>");
	</script>
    <script type="text/javascript">
        Participation.eventName = "<%= j @event.name %>";
        Participation.eventDate = "<%= j @event.date.strftime('%B %d, %Y') %>";
        Participation.url = "<%= j(request.protocol + request.host_with_port + volunteer_participation_path(@volunteer, @participation)) %>";
        Participation.volunteerName = "<%= j @volunteer.full_name %>"
    </script>
<% end %>

app/views/participations/thank_form.html.erb
<div class="page-header">
  <h1>Send A Thank-You</h1>
</div>

<%= form_tag do %>
  <%= hidden_field_tag :donation_id, params[:donation_id] %>

  <%= hidden_field_tag :donation_type, params[:donation_type] %>

  <div class="control-group">
    <label class="control-label">To</label>
    <div class="controls">
      <%= @donation.email %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">From</label>
    <div class="controls">
      <%= @volunteer.email %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Subject</label>
    <div class="controls">
      <%= text_field_tag :subject, "Thank you for supporting me in #{@event.name}", :class => 'span6'%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Message</label>
    <div class="controls">
      <%= text_area_tag :message, interpolate_email(@event.thank_you_email, @participation, @donation.name), :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= submit_tag 'Submit', :class => 'btn btn-primary submit-button' %>
    <%= link_to 'Cancel', volunteer_participation_url(@participation.volunteer, @participation), :class => 'btn' %>
  </div>
<% end %>