config/routes.rb
Fundit::Application.routes.draw do
  get "home/index"

  resources :organizations do
    member do
      post 'follow'
      delete 'unfollow'
    end
    collection do
      get 'new_stripe'
    end

    resources :events
  end

  resources :events
  
  resources :volunteers

  resources :volunteers do
    resources :participations do
      member do
        get 'donate', :as => 'donate', :action => 'show'
        post 'donate'
        get 'thank', :as => 'thank', :action => 'thank_form'
        post 'thank'

        get 'offline_donate', :as => 'offline_donate', :action => 'offline_donate_form'
        post 'offline_donate'
      end
    end
  end

  match '/login' => 'sessions#new', :via => :get, :as => 'login'
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :via => :delete, :as => 'logout'

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :name, :date, :solicit_email, :thank_you_email, :time, :location, :image_url
  belongs_to :organization
  has_many :participations
  has_many :volunteers, :through => :participations

  validates :name, :organization_id, :date, :time, :location, :presence => true

  after_initialize :init_msgs

  def init_msgs
    return unless new_record?

    self.solicit_email = <<-END_EMAIL.strip_heredoc
      Dear Friends,

      On {{date}}, I will be participating in {{name}} to support {{org}}. I'm writing to you to ask that you support me with a donation. You can donate online and track my progress at {{link}}.

      Thank you,
      {{volunteer}}
    END_EMAIL

    self.thank_you_email = <<-END_EMAIL.strip_heredoc
      Dear {{donor}},

      Thank you for supporting my participation in {{name}} to raise money for {{org}}. Your generous donation will help me achive my funraising goal. You can track my progress at {{link}}.

      Thank you for your support,
      {{volunteer}}
    END_EMAIL
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_organization, :except => [:show, :index]
  before_filter :find_event, :except => [:new, :create, :index]
  before_filter :require_ownership, :only => [:edit, :update]

	# GET /events
  # GET /events.json
  def index
    @events = Event.where("date >= ?", Date.today).order(:date).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end


  # GET /organizations/1/events/1
  # GET /organizations/1/events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /organizations/1/events/new
  # GET /organizations/1/events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /organizations/1/events/1/edit
  def edit
  end

  # POST /organizations/1/events
  # POST /organizations/1/events.json
  def create
    @event = Event.new(params[:event])
    @event.organization = current_user

    respond_to do |format|
      if @event.save

        @event.organization.follows.each do | follow |    
          Pony.mail :to => "\"#{follow.volunteer.name}\" <#{follow.volunteer.email}>",
                :from => "FundIt <fundit@fundit.org>",
                :subject => "#{@event.organization.name} created a new FundIt event #{@event.name}.",
                :body => "Check it out at http://fundit.herokuapp.com/organizations/#{@event.organization.id}/events/#{@event.id}."
        end

        format.html { redirect_to organization_event_url(@event.organization, @event), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1/events/1
  # PUT /organizations/1/events/1.json
  def update
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to organization_event_url(@event.organization, @event), notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def require_ownership
    unless @event.organization == current_user
      redirect_to root_url, :alert => "You don't own that event."
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [current_user, @event],:html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
    	<div class="input-append date">
      	<%= f.text_field :date, :class => 'date-input input-small', :id => 'foo',
                       "data-date" => @event.date ? @event.date.strftime : Date.today.strftime,
                       "data-date-format" => "yyyy-mm-dd" %>
     	 	<span class="add-on">
					<i class="icon-calendar"></i>
				</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time, :class => 'control-label' %>
    <div class="controls">
    	<div class="input-append">
    		<%- time_string = @event.time ? @event.time.strftime("%I:%M %p") : Time.now.strftime("%I:00 %p") -%>
				<%= f.text_field :time, :class => 'time-input input-small', :value => time_string %>
				<span class="add-on">
					<i class="icon-time"></i>
				</span>
    	</div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image_url, "Event Image", :class => 'control-label' %>
    <div class="controls">
      <a class="btn filepicker-btn">Pick a file</a>
      <br /><br />
      <%= profile_event_image_tag_for @event %>
      <%= f.hidden_field :image_url, :id => 'avatar_url_field' %>
    </div>
  </div>
  <div class="control-group">
    <label>Canned Messages</label>
    <div class="controls">
      Help your volunteers out by providing them messages to send to their
      donors. You can use <code>{{date}}</code> to insert the date
      of your event, <code>{{name}}</code> to insert the name of your event,
      <code>{{org}}</code> to insert the name of your organization,
      <code>{{link}}</code> to insert a link to the participation page,
      and <code>{{volunteer}}</code> in insert the name of the volunteer
      sending the message. For a thank-you message, you can also use
      <code>{{donor}}</code> to insert the donor's name.

      <ul class="nav nav-tabs">
        <li class="active"><a href="#msg-solicit" data-toggle="tab">Solicitation</a></li>
        <li><a href="#msg-thank-you" data-toggle="tab">Thank-You</a></li>
      </ul>
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="msg-solicit">
          Volunteers will be prompted to send this message to their friends to
          solicit donations.

          <%= f.text_area :solicit_email, :class => 'text_area' %>
        </div>
        <div class="tab-pane fade" id="msg-thank-you">
          Volunteers will be prompted to send this email to donors who
          contribute money to them.
          <%= f.text_area :thank_you_email, :class => 'text_area' %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', root_url, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
  <h1>Edit Event</h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<div class="row">
	<div class="search-side-bar span4">
		<h1> Upcoming Events </h1>
		<p class="info">New events are added daily by our various organizations.</p>
		<input type="text" class="search-query span4" placeholder="Search" data-deletable>
	</div>
	<div class="search-table-center span7">
		<div class="hero-unit">
			<div class="hero-unit-header">
				<h2 class="main-header">Upcoming Events (<%= @events.size %>)</h2>
				<h3 class="search-header"></h3>
			</div>
				<% if @events.empty? %>
						<p>No upcoming events.</p>
				<% else %>
					<% @events.each do |event| %>
						<div class="search-table-entry">
							<%= icon_event_image_tag_for event %>
							<div class="entry-text">
								<div class="info">On <strong><%= event.date ? event.date.strftime('%B %d') : 'none' %></strong> hosted by <strong><%= event.organization.name %></strong></div>
								<div class="title"><%= link_to event.name, event_path(event) %></div>
							</div>
						</div>
					<% end %>
				<% end %>
		</div>

	</div>
</div>

<% content_for :additional_scripts do %>
    <script type="text/javascript">
			$('#events_nav').addClass("active");
    </script>
<% end %>

app/views/events/new.html.erb
<div class="page-header">
  <h1>New Event</h1>
</div>
<%= render :partial => 'form' %>

<% content_for :additional_scripts do %>
    <script type="text/javascript">
            $('#create_event_nav').addClass("active");
    </script>
<% end %>

app/views/events/show.html.erb
<div class="info-header">
		<div class="row">
			<div class="span2">
			<%= profile_event_image_tag_for @event %>
			</div>
			<div class="details span7">
				<p class="small-heading"> 
					Hosted by <%= @event.organization.name %>
				</p>
				<div class="heading-div">
					<p class="heading">
						<%= @event.name %>
					</p>
				</div>
				<p class="info-links">
					<%= link_to organization_path(@event.organization)  do %>
                            <i class="icon-user"></i>
                            More about <%= @event.organization.name %>
          <% end %>
				</p>
			</div>
			<div class="span3 controls-header">
				<% if @event.organization == current_user %>
					<%= link_to 'Edit Event', edit_organization_event_path(@event.organization, @event), :class => 'btn btn-edit' %>
				<% elsif !(current_user.kind_of? Organization) %>
					<%= link_to 'Participate', new_volunteer_participation_path(current_user || 0, :event_id => @event.id), :class => 'btn btn-warning' %>
				<% end %>
			</div>
		</div>
	</div>

  <div class="row-fluid">
		<div class="span7 sidebar">
			<table>
				<tr>
					<td class="table-label">DATE</td>
					<td class="semibold"><%= @event.date ? @event.date.strftime('%B %d, %Y') : 'none' %></td>
				</tr>
				<tr>
					<td class="table-label">TIME</td>
					<td class="semibold"><%= @event.time ? @event.time.strftime('%I:%M %p') : 'none'%></td>
				</tr>
				<tr>
					<td class="table-label">LOCATION</td>
					<td class="semibold"><%= @event.location %></td>
				</tr>
				<tr>
					<td class="table-label"> DETAILS </td>
					<td class="linebreak"><%= @event.description %></td>
				</tr>
			</table>
		</div>
		<div class="span6 main-content">
			<div class="hero-unit">
				<div class="hero-unit-header">
					<h2>Participants (<%= @event.participations.length %>)</h2>
				</div>
            <% if @event.participations.empty? %>
                <p>No participants yet.</p>
            <% else %>
        			<% @event.participations.each do |participation| %>
            		<div class="search-table-entry">
            			<%= mini_icon_image_tag_for participation.volunteer %>
            			<div class="entry-text">
        						<%= link_to participation.volunteer.full_name , volunteer_participation_path(participation.volunteer, participation) %>
        					</div>
        				</div>
        			<% end %>
            <% end %>
      </div>
		</div>
	</div>
</div>