config/routes.rb
Fundit::Application.routes.draw do
  get "home/index"

  resources :organizations do
    member do
      post 'follow'
      delete 'unfollow'
    end
    collection do
      get 'new_stripe'
    end

    resources :events
  end

  resources :events
  
  resources :volunteers

  resources :volunteers do
    resources :participations do
      member do
        get 'donate', :as => 'donate', :action => 'show'
        post 'donate'
        get 'thank', :as => 'thank', :action => 'thank_form'
        post 'thank'

        get 'offline_donate', :as => 'offline_donate', :action => 'offline_donate_form'
        post 'offline_donate'
      end
    end
  end

  match '/login' => 'sessions#new', :via => :get, :as => 'login'
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :via => :delete, :as => 'logout'

  root :to => 'home#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :bio, :email, :name, :password, :password_confirmation,
                  :stripe_token, :stripe_code, :stripe_pub_key, :avatar_url

  has_many :events
  has_many :follows
  has_secure_password

  validate :email_must_be_unique
  validates :password, :presence => true, :on => :create
  validates :email, :name, :stripe_token, :presence => true

  # attr_accessor stripe_code so we can use it in the signup form -- we convert
  # a stripe_code (which Stripe gives us when an OAuth request is redirected
  # back to us) to a stripe_token during a before_validation.
  attr_accessor :stripe_code

  before_validation :convert_stripe_code, :on => :create

  private

  # Returns true if the current user already follows the organization
  def self.follow_already(currentuserid, organizationid)
    follow = Follow.where("volunteer_id=?", currentuserid).where("organization_id=?", organizationid).first
    if follow
      return true
    else
      return false
    end
  end

  # Validation to ensure emails are unique across both Merchants and Customers.
  def email_must_be_unique
    if ((Organization.where(['email = ? AND id <> ?', self.email, self.id]).count > 0) or
        (Volunteer.where(['email = ?', self.email]).count > 0))

      errors.add(:email, "is already taken")
    end
  end

  # Convert an OAuth code to a Stripe token we can use to make charges
  def convert_stripe_code
    tokens = STRIPE_OAUTH.auth_code.get_token(self.stripe_code, {
      :headers => {'Authorization' => "Bearer #{STRIPE_KEYS['secret_key']}"}
    })
    self.stripe_token = tokens.token
    self.stripe_pub_key = tokens.params['stripe_publishable_key']

    return true
  end
  
  def number_followers
  	return follows.size
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :require_organization, :only => [:edit, :update]
  before_filter :find_organization, :except => [:index, :new, :create, :new_stripe]
  before_filter :require_ownership, :only => [:edit, :update]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.order(:name).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    if current_user
      @followalready = Organization.follow_already(current_user.id, @organization.id)
    end

    @futureevents = @organization.events.where(['date >= ?', DateTime.now])
    @pastevents = @organization.events.where(['date < ?', DateTime.now])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new_stripe
  # prompts the user to connect to Stripe
  def new_stripe
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        session[:user_id] = @organization.id
        session[:user_type] = 'Organization'
        format.html { redirect_after_login }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /organizations/1/follow
  def follow
    if Organization.follow_already(current_user.id, @organization.id)
      respond_to do |format|
        format.html { redirect_to @organization, notice: 'You already follow the organization.' }
      end
    else
      @follow = Follow.new(params[:follow])

      @follow.volunteer_id = current_user.id
      @follow.organization_id = params[:id]

      respond_to do |format|
        if @follow.save
          format.html { redirect_to @organization, notice: 'Follow was successfully created.' }
          format.json { render json: @organization, status: :created, location: @organization }
        end
      end
    end
  end

  # DELETE /organizations/1/unfollow
  def unfollow
    @follow = Follow.where("volunteer_id=?", current_user.id).where("organization_id=?", params[:id]).first()
    if @follow
      @follow.destroy
      respond_to do |format|
        format.html { redirect_to @organization, notice: 'You have successfully unfollowed the organization.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @organization, notice: 'You were not following the organization.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def find_organization
    @organization = Organization.find(params[:id])
  end

  def require_ownership
    unless @organization == current_user
      redirect_to root_url, :alert => "You don't own that organization."
    end
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<% if @organization.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

    <ul>
    <% @organization.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @organization, :html => { :class => 'form-horizontal' } do |f| %>
  <%# If we have a stripe code, include it as a hidden field %>
  <% if params[:code] %>
    <input type="hidden" name="organization[stripe_code]" value="<%= params[:code] %>" />
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :avatar_url, "Profile Image", :class => 'control-label' %>
    <div class="controls">
      <a class="btn filepicker-btn">Pick a file</a>
      <br /><br />
      <%= profile_image_tag_for @organization %>
      <%= f.hidden_field :avatar_url, :id => 'avatar_url_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, 'Confirm Password', :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :bio, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', organizations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<div class="page-header">
  <h1>Edit Organization</h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/index.html.erb
<div class="row">
	<div class="search-side-bar span4">
		<h1> Organizations </h1>
		<p class="info"> Fundit partners with organizations all over the country. Find the organization that fits your cause.</p>
		<input type="text" class="search-query span4" placeholder="Search" data-deletable>
	</div>
	<div class="search-table-center span7">
		<div class="hero-unit">
			<div class="hero-unit-header"><h2>Popular Organizations</h2></div>
				<% Organization.order("follows_count DESC").limit(3).each do |organization| %>
					<div class="search-table-entry highlight">
						<%= icon_image_tag_for organization %>
						<span><%= link_to organization.name, organization_path(organization) %><span>
					</div>
				<% end %>
			<div class="hero-unit-header margin-top">
				<h2 class="main-header">All Organizations (<%= @organizations.size %>)</h2>
				<h3 class="search-header"></h3>
			</div>
				<% @organizations.each do |organization| %>
					<div class="search-table-entry">
						<%= icon_image_tag_for organization %>
						<span><%= link_to organization.name, organization_path(organization) %><span>
					</div>
				<% end %>
			</div>
		</div>

	</div>
</div>


<% content_for :additional_scripts do %>
    <script type="text/javascript">
			$('#organizations_nav').addClass("active");
    </script>
<% end %>

app/views/organizations/new.html.erb
<div class="page-header">
  <h1>New Organization</h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/new_stripe.html.erb
<div class="page-header">
  <h1>Connect to Stripe</h1>
</div>
<p>
    To allow FundIt to collection donations on your behalf, you
    need to connect FundIt to a Stripe account. Stripe is a
    secure payment processor, similar to PayPal. Stripe will
    deposit funds donated to your organization directly to your
    bank account. If you don't have a Stripe account, you'll be
    prompted to crate one.
</p>
<p class="stripe-connect-btn">
    <a href="<%= STRIPE_OAUTH.auth_code.authorize_url(:scope => 'read_write') %>">
        <img src="/assets/stripe-connect.png" width="190" height="33" data-hires="true">
    </a>
</p>

app/views/organizations/show.html.erb
<div class="info-header">
		<div class="row">
			<div class="span2">
			<%= profile_image_tag_for @organization %>
			</div>
			<div class="details span6">
				<div class="heading-div">
					<p class="heading"><%= @organization.name %></p>
				</div>
				<p class="follows-count">
					<% if @organization.follows.length == 1 %>
						<strong><%= @organization.follows.length %></strong> Follower
					<% else %>
						<strong><%= @organization.follows.length %></strong> Followers
					<% end %>
				</p>
			</div>
				<% if current_user %>
					<% if current_user == @organization %>
					<div class="span3 controls-border">
						<%= link_to 'Edit Organization', edit_organization_path(@organization) %>
						<%= link_to "CREATE EVENT", new_organization_event_path(@organization) %>
					</div>
					<% else %>
					<div class="span4 controls-header">
						<% if @followalready %>
							<%= link_to 'Unfollow', unfollow_organization_path, :method => :delete, :class => 'btn btn-warning' %>
						<% else %>
							<%= link_to 'Follow', follow_organization_path, :method => :post, :class => 'btn btn-warning' %>
						<% end %>
					</div>
					<% end %>
				<% end %>
		</div>
	</div>

  <div class="row-fluid">
		<div class="span7 sidebar">
			<table>
				<tr>
					<td class="table-label">EMAIL</td>
					<td class="semibold"><%= @organization.email %></td>
				</tr>
				<tr>
					<td class="table-label"> ABOUT</td>
					<td class="linebreak"><%= @organization.bio %></td>
				</tr>
			</table>
		</div>
		<div class="span6 main-content">
			<div class="hero-unit">
				<div class="hero-unit-header">
					<h2>Upcoming Events (<%= @futureevents.length %>)</h2>
				</div>
				<% if @futureevents.empty? %>
						<p>No upcoming events.</p>
				<% else %>
					<% @futureevents.each do |event| %>
						<div class="event" id=<%=event.id %>>
							<%= link_to event.name, organization_event_path(@organization, event) %>
							<span class="moredetails">
								<div class="expandbtn">+</div>
								<div class="hiddeninfo hidden"%>
										<div class="eventdescription">
											<p><strong><%= event.date ? event.date.strftime('%B %d, %Y') : 'none' %></strong></p>
											<div class="linebreak"><%= event.description %></div>
										</div>
									</div>
							</span>
						</div>
					<% end %>
				<% end %>
				<div class="hero-unit-header">
					<h2>Past Events (<%= @pastevents.length %>)</h2>
				</div>
					<% if @pastevents.empty? %>
						<p>No past events.</p>
					<% else %>
						<% @pastevents.each do |event| %>
							<div class="event" id=<%=event.id %>>
								<%= link_to event.name, organization_event_path(@organization, event) %>
								<span class="moredetails">
									<div class="expandbtn">+</div>
									<div class="hiddeninfo hidden"%>
										<div class="eventdescription">
											<p><strong><%= event.date ? event.date.strftime('%B %d, %Y') : 'none' %></strong></p>
											<div class="linebreak"><%= event.description %></div>
										</div>
									</div>
								</span>
							</div>
						<% end %>
					<% end %>
      </div>
		</div>
	</div>
</div>

<% content_for :additional_scripts do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.hiddeninfo').hide();
      
      $('.moredetails').live('click', function(){
        if($(this).children('.hiddeninfo').is(':hidden')){
          $(this).children('.expandbtn').html('-');
          $(this).children('.hiddeninfo').slideDown();
        }else{
          $(this).children('.expandbtn').html('+');
          $(this).children('.hiddeninfo').slideUp();
        }
      });
    });
  </script>
  
<% end %>