config/routes.rb
Fundit::Application.routes.draw do
  get "home/index"

  resources :organizations do
    member do
      post 'follow'
      delete 'unfollow'
    end
    collection do
      get 'new_stripe'
    end

    resources :events
  end

  resources :events
  
  resources :volunteers

  resources :volunteers do
    resources :participations do
      member do
        get 'donate', :as => 'donate', :action => 'show'
        post 'donate'
        get 'thank', :as => 'thank', :action => 'thank_form'
        post 'thank'

        get 'offline_donate', :as => 'offline_donate', :action => 'offline_donate_form'
        post 'offline_donate'
      end
    end
  end

  match '/login' => 'sessions#new', :via => :get, :as => 'login'
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :via => :delete, :as => 'logout'

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:url" content=<%= request.fullpath %>/> 
    <title><%= content_for?(:title) ? yield(:title) : "FundIt" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body class="<%= controller.controller_name %> <%= controller.action_name %>">

    <div class="wrapper">
      <div class="navbar navbar-static-top">
        <div class="navbar-inner">
          <div class="container">
          	<div class="row">
          		<div class="span3">
  							<a class="brand" href="/">Fund<strong class="accent-color">It</strong></a>
            	</div>
            	<div class="span9">
            		<div class="row">
  							<% if current_user %>
  								<ul class="navbar-text pull-right unstyled">
  									<% if current_user.kind_of? Volunteer %>
  										<li>Welcome <strong class="link-dark"><%= link_to current_user.name, volunteer_path(current_user) %></strong>.
  									<% else %>
  										<li>Welcome <strong class="link-dark"><%= link_to current_user.name, organization_path(current_user) %></strong>.
  									<% end %>
  									<span> Not you? </span>
  									<strong class="link-color"><%= link_to 'Logout', logout_path, :method => 'delete' %></strong></li>
  								</ul>
  							<% else %>
  									<ul class="navbar-text pull-right unstyled">
  										<li><%= link_to 'Login', login_path %></li>
  									</ul>
  							<% end %>
  							</div>
  							<div class="row">
  							<ul class="nav pull-right nav-links">
  								<li><%= link_to "ORGANIZATIONS", organizations_path , :id=>"organizations_nav"%></li>
  								<li><%= link_to "EVENTS", events_path, :id=>"events_nav" %></li>
  								<li><%= link_to "VOLUNTEERS", volunteers_path, :id=>"volunteers_nav" %></li>
  							</ul>
  							</div>
  						</div>
  					</div>
          </div>
        </div>
      </div>

      <div class="container content-container">
        <div class="content">
          <% if flash[:alert] %>
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= flash[:alert] %>
            </div>
          <% end %>

          <% if flash[:notice] %>
            <div class="alert">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= flash[:notice] %>
            </div>
          <% end %>

          <%= yield %>
        </div>

      </div>
      <div class="push"></div>
    </div>

    <div class="bottom">
      Created for <a href="https://stellar.mit.edu/S/course/6/fa12/6.170/">6.170</a>
      by Ben Weissmann, Joanna Kao, and Cristina Lozano. Source on
      <a href="https://github.com/6170/fundit">GitHub</a>.
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
    <script type="text/javascript">
      filepicker.setKey("<%= j FILEPICKER_KEYS['api_key'] %>");
    </script>
    <script type="text/javascript">
      $(document).ready(function(){
      	$('.linebreak').each(function() {
      		$(this).html($(this).text().replace(/\n\r?/g, '<br />'))
      		});
      });
    </script>

    <%= yield :additional_scripts %>
  </body>
</html>